// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxtk_KnWFVFT0pf4iS9i7FRMaowlEHihw',
    appId: '1:1064134904565:web:d0bda90c753d65a32c53bc',
    messagingSenderId: '1064134904565',
    projectId: 'vault-manager-e6241',
    authDomain: 'vault-manager-e6241.firebaseapp.com',
    storageBucket: 'vault-manager-e6241.appspot.com',
    measurementId: 'G-QJNM693X7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZflwLbh4YX-QwC4LxQx8OZMeQIsXUABE',
    appId: '1:1064134904565:android:2967662c577a76222c53bc',
    messagingSenderId: '1064134904565',
    projectId: 'vault-manager-e6241',
    storageBucket: 'vault-manager-e6241.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8vgmFPqgCtKkgmK9BF67zbVIA7QR1bxU',
    appId: '1:1064134904565:ios:1c8779537ed75dc92c53bc',
    messagingSenderId: '1064134904565',
    projectId: 'vault-manager-e6241',
    storageBucket: 'vault-manager-e6241.appspot.com',
    iosClientId: '1064134904565-btlg5vve08e2un5tbeq11t3ln7icv5a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.vaultManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8vgmFPqgCtKkgmK9BF67zbVIA7QR1bxU',
    appId: '1:1064134904565:ios:1c8779537ed75dc92c53bc',
    messagingSenderId: '1064134904565',
    projectId: 'vault-manager-e6241',
    storageBucket: 'vault-manager-e6241.appspot.com',
    iosClientId: '1064134904565-btlg5vve08e2un5tbeq11t3ln7icv5a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.vaultManager',
  );
}
